/**
 * Server-side HTML sanitizer
 *
 * Used before any `dangerouslySetInnerHTML` to prevent XSS from AI-generated
 * product descriptions, Shopify blog content, and Markdown-converted HTML.
 *
 * Allowlist approach: only safe tags and attributes pass through.
 * All event handlers (onclick, onerror, ...) and unsafe protocols
 * (javascript:, data:, vbscript:) are stripped.
 */

import sanitizeHtml from 'sanitize-html';

/** Tags allowed in rich product/blog HTML generated by AI or Shopify */
const ALLOWED_TAGS = [
  // Block
  'article', 'aside', 'blockquote', 'br', 'caption', 'div', 'dt', 'dd',
  'figcaption', 'figure', 'footer', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
  'header', 'hr', 'li', 'main', 'nav', 'ol', 'p', 'pre', 'section',
  'summary', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'ul',
  // Inline
  'a', 'abbr', 'b', 'cite', 'code', 'del', 'em', 'i', 'ins', 'kbd',
  'mark', 'q', 's', 'samp', 'small', 'span', 'strong', 'sub', 'sup',
  'time', 'u', 'var',
];

/** Attributes allowed on all elements (per-tag overrides below) */
const ALLOWED_ATTRS: sanitizeHtml.IOptions['allowedAttributes'] = {
  '*': ['class', 'id', 'data-*'],
  a: ['href', 'title', 'target', 'rel'],
  img: ['src', 'srcset', 'alt', 'title', 'width', 'height', 'loading'],
  td: ['colspan', 'rowspan'],
  th: ['colspan', 'rowspan', 'scope'],
  time: ['datetime'],
};

/** Protocols allowed in href / src */
const ALLOWED_SCHEMES = ['http', 'https', 'mailto', 'tel'];

/**
 * Sanitize HTML for safe server-side rendering.
 * Returns empty string if input is null/undefined.
 */
export function sanitize(html: string | null | undefined): string {
  if (!html) return '';
  return sanitizeHtml(html, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: ALLOWED_ATTRS,
    allowedSchemes: ALLOWED_SCHEMES,
    allowedSchemesByTag: {
      a: ALLOWED_SCHEMES,
      img: ['http', 'https', 'data'], // data: URI images are OK in <img>
    },
    // Strip all event handlers even if somehow listed above
    disallowedTagsMode: 'discard',
  });
}

/**
 * Sanitize a simple inline HTML string produced by Markdown bold conversion.
 * Only allows <strong>, <em>, <a>, <code>, <br>.
 */
export function sanitizeInline(html: string | null | undefined): string {
  if (!html) return '';
  return sanitizeHtml(html, {
    allowedTags: ['strong', 'em', 'a', 'code', 'br', 'span'],
    allowedAttributes: {
      '*': ['class'],
      a: ['href', 'rel', 'target'],
    },
    allowedSchemes: ALLOWED_SCHEMES,
    disallowedTagsMode: 'discard',
  });
}
